apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngineMount
metadata:
  name: "{{ .Release.Name }}"
  labels:
    {{- include "cockroach-serverless.labels" . | nindent 4 }}  
spec:
  authentication: 
    path: kubernetes
    role: database-engine-admin
  type: database
  path: "{{ .Values.application }}-{{ .Values.environment }}"