apiVersion: redhatcop.redhat.io/v1alpha1
kind: DatabaseSecretEngineRole
metadata:
  name: "{{ include "cockroach-serverless.fullname" . }}"
  labels:
    {{- include "cockroach-serverless.labels" . | nindent 4 }}  
spec:
  authentication: 
    path: kubernetes
    role: database-engine-admin
  path: "{{ .Values.application }}-{{ .Values.environment }}/{{ include "cockroach-serverless.fullname" . }}"
  defaultTTL: 1h0m0s
  maxTTL: 24h0m0s
  dBName: defaultdb
  creationStatements:
    - CREATE ROLE "{{ "{{name}}" }}" WITH LOGIN PASSWORD '{{ "{{password}}" }}' VALID UNTIL '{{ "{{expiration}}" }}'; GRANT SELECT ON ALL TABLES IN SCHEMA public TO "{{ "{{name}}" }}";