apiVersion: dbaas.redhat.com/v1alpha1
kind: DBaaSConnection
metadata:
  name: "{{ .Release.Name }}"
  labels:
    {{- include "cockroach-serverless.labels" . | nindent 4 }}
spec:
  instanceID: dummy
  inventoryRef:
    name: backstage-demo
    namespace: openshift-dbaas-operator