apiVersion: redhatcop.redhat.io/v1alpha1
kind: DatabaseSecretEngineConfig
metadata:
  name: "{{ .Release.Name }}"
  labels:
    inject-username: cockroach-serverless
    {{- include "cockroach-serverless.labels" . | nindent 4 }}      
spec:
  authentication: 
    path: kubernetes
    role: database-engine-admin
  pluginName: postgresql-database-plugin
  allowedRoles:
    - "{{ .Release.Name }}-read-only"
    - "{{ .Release.Name }}-read-write"    
  connectionURL: dummy
  rootCredentials:
    secret:
      name: crdb-cloud-user-credentials-{{ .Release.Name }}
    passwordKey: password
  path: "{{ .Values.application }}-{{ .Values.environment }}/{{ .Release.Name }}"
  username: dummy