apiVersion: dbaas.redhat.com/v1alpha1
kind: DBaaSInstance
metadata:
  name: "{{ include "cockroach-serverless.fullname" . }}"
  labels:
    {{- include "cockroach-serverless.labels" . | nindent 4 }} 
spec: 
  cloudProvider: AWS
  cloudRegion: us-west-2 
  inventoryRef:
    name: backstage-demo
    namespace: openshift-dbaas-operator
  name: "{{ .Values.application }}-{{ .Values.environment }}-{{ include "cockroach-serverless.fullname" . }}"    
