apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "dotnet-build.fullname" . }}-repo-auth"
  labels:
    {{- include "dotnet-build.labels" . | nindent 4 }}
  annotations:
    build.openshift.io/source-secret-match-uri-1: https://github.com/{{ .Values.github.owner }}/{{ .Values.github.repo_name }}
type: kubernetes.io/basic-auth
data:
  password: "{{ .Values.github.pat | b64enc }}"