apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include ".quarkus-pipeline.fullname" . }}-code-workspace
  labels:
    {{- include "quarkus-pipeline.labels" . | nindent 4 }}  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi