name: build and deploy a quarkus application
on:
  workflow_call:
    inputs: 
      app:
        description: 'the name of the app this repo belongs to'
        required: true
        type: string

jobs:
  java-build:
    runs-on: [self-hosted, "${{ inputs.app }}"]
    steps:
    - name: set repo name
      shell: bash
      run: | 
        echo "REPOSITORY_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV        

    - name: checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Static code check (Emulated)
      run: |
        echo noop

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build
      run: |
        ./mvnw -B -DskipTests clean package --file pom.xml

# TODO change this into an s2i build
  image-build:
    runs-on: [self-hosted, "${{ inputs.app }}"]
    needs: java-build
    steps:
    - name: set repo name
      shell: bash
      run: | 
        echo "REPOSITORY_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV

    # - name: set ocp token
    #   shell: bash
    #   run: | 
    #     echo "KUBERNETES_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" >> $GITHUB_ENV
    #     echo "KUBERNETES_CA=$(cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt)" >> $GITHUB_ENV
    
    - name: Install CLI tools from OpenShift Mirror
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: "4"
        helm: "3.6.2"
        skip_cache: true
                
    - name: checkout code
      uses: actions/checkout@v2

    # - name: kubernetes login
    #   uses: redhat-actions/oc-login@v1
    #   with:
    #     # URL to your OpenShift cluster.
    #     # Refer to Step 2.
    #     openshift_server_url: https://kubernetes.default.svc:443

    #     # Authentication Token. Can use username and password instead.
    #     # Refer to Step 3.
    #     openshift_token: ${{ env.KUBERNETES_TOKEN }}

    #     certificate_authority_data: ${{ env.KUBERNETES_CA }}

    #     # Optional - this sets your Kubernetes context's current namespace after logging in.
    #     namespace: ${{ inputs.app }}-build       

    - name: deploy build-config
      shell: bash
      run: | 
        helm --debug --kube-apiserver https://kubernetes.default.svc:443 --kube-ca-file /var/run/secrets/kubernetes.io/serviceaccount/ca.crt --kube-token $(cat /var/run/secrets/kubernetes.io/serviceaccount/token) \
        upgrade --repo https://raf-backstage-org.github.io/shared-workflows --version "0.1.0" ${{ env.REPOSITORY_NAME }} quarkus-build -i -n ${{ inputs.app }}-build \
        --set github.owner=${{ github.repository_owner }} --set github.repo_name=${{ env.REPOSITORY_NAME }} --set github.commit_sha=${{ github.sha }} --set github.pat=${{ github.token }} \
        --set nameOverride ${{ inputs.app }}

    - name: start and follow the build
      shell: bash
      run: | 
        oc start-build ${{ env.REPOSITORY_NAME }}-${{ env.REPOSITORY_NAME }}-build -F -n ${{ inputs.app }}-build

  deploy-dev:
    runs-on: [self-hosted, "${{ inputs.app }}"]
    needs: image-build
    steps:
    - name: set repo name
      shell: bash
      run: | 
        echo "REPOSITORY_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV
    
    - name: Install CLI tools from OpenShift Mirror
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: "4"
        helm: "3.6.2"
        skip_cache: true
                
    - name: checkout code
      uses: actions/checkout@v2
  
    - name: deploy deploy app
      shell: bash
      run: | 
        helm --debug --kube-apiserver https://kubernetes.default.svc:443 --kube-ca-file /var/run/secrets/kubernetes.io/serviceaccount/ca.crt --kube-token $(cat /var/run/secrets/kubernetes.io/serviceaccount/token) \
        upgrade --repo https://raf-backstage-org.github.io/shared-workflows --version "0.1.0" ${{ env.REPOSITORY_NAME }} quarkus-run -i -n ${{ inputs.app }}-dev \
        --set image.repository=quay.io/${{ github.repository_owner }}/${{ env.REPOSITORY_NAME }} --set image.tag=${{ github.sha }} \
        --set nameOverride ${{ inputs.app }}

    - name: integration tests (emulated)
      run: |
        echo noop

  deploy-qa:
    runs-on: [self-hosted, "${{ inputs.app }}"]
    needs: deploy-dev
    steps:
    - name: set repo name
      shell: bash
      run: | 
        echo "REPOSITORY_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV
    - name: Install CLI tools from OpenShift Mirror
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: "4"
        helm: "3.6.2"
        skip_cache: true
                
    - name: checkout code
      uses: actions/checkout@v2
  
    - name: deploy app
      shell: bash
      run: | 
        helm --debug --kube-apiserver https://kubernetes.default.svc:443 --kube-ca-file /var/run/secrets/kubernetes.io/serviceaccount/ca.crt --kube-token $(cat /var/run/secrets/kubernetes.io/serviceaccount/token) \
        upgrade --repo https://raf-backstage-org.github.io/shared-workflows --version "0.1.0" ${{ env.REPOSITORY_NAME }} quarkus-run -i -n ${{ inputs.app }}-qa \
        --set image.repository=quay.io/${{ github.repository_owner }}/${{ env.REPOSITORY_NAME }} --set image.tag=${{ github.sha }} \
        --set nameOverride ${{ inputs.app }}

    - name: integration tests (emulated)
      run: |
        echo noop


  deploy-prod:
    runs-on: [self-hosted, "${{ inputs.app }}"]
    needs: deploy-qa
    steps:
    - name: set repo name
      shell: bash
      run: | 
        echo "REPOSITORY_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV
    - name: Install CLI tools from OpenShift Mirror
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: "4"
        helm: "3.6.2"
        skip_cache: true
                
    - name: checkout code
      uses: actions/checkout@v2
  
    - name: deploy deploy app
      shell: bash
      run: | 
        helm --debug --kube-apiserver https://kubernetes.default.svc:443 --kube-ca-file /var/run/secrets/kubernetes.io/serviceaccount/ca.crt --kube-token $(cat /var/run/secrets/kubernetes.io/serviceaccount/token) \
        upgrade --repo https://raf-backstage-org.github.io/shared-workflows --version "0.1.0" ${{ env.REPOSITORY_NAME }} quarkus-run -i -n ${{ inputs.app }}-qa \
        --set image.repository=quay.io/${{ github.repository_owner }}/${{ env.REPOSITORY_NAME }} --set image.tag=${{ github.sha }} \
        --set nameOverride ${{ inputs.app }}
        
    - name: integration tests (emulated)
      run: |
        echo noop